config/routes.rb
Rails.application.routes.draw do
  resources :resturants
  get 'pages/about'

  get 'pages/contact'

  root 'resturants#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/resturant.rb
class Resturant < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/resturants_controller.rb
class ResturantsController < ApplicationController
  before_action :set_resturant, only: [:show, :edit, :update, :destroy]

  # GET /resturants
  # GET /resturants.json
  def index
    @resturants = Resturant.all
  end

  # GET /resturants/1
  # GET /resturants/1.json
  def show
  end

  # GET /resturants/new
  def new
    @resturant = Resturant.new
  end

  # GET /resturants/1/edit
  def edit
  end

  # POST /resturants
  # POST /resturants.json
  def create
    @resturant = Resturant.new(resturant_params)

    respond_to do |format|
      if @resturant.save
        format.html { redirect_to @resturant, notice: 'Resturant was successfully created.' }
        format.json { render :show, status: :created, location: @resturant }
      else
        format.html { render :new }
        format.json { render json: @resturant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resturants/1
  # PATCH/PUT /resturants/1.json
  def update
    respond_to do |format|
      if @resturant.update(resturant_params)
        format.html { redirect_to @resturant, notice: 'Resturant was successfully updated.' }
        format.json { render :show, status: :ok, location: @resturant }
      else
        format.html { render :edit }
        format.json { render json: @resturant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resturants/1
  # DELETE /resturants/1.json
  def destroy
    @resturant.destroy
    respond_to do |format|
      format.html { redirect_to resturants_url, notice: 'Resturant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resturant
      @resturant = Resturant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resturant_params
      params.require(:resturant).permit(:name, :phone, :website)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/resturants_helper.rb
module ResturantsHelper
end

app/views/layouts/_bootstrap.html.erb
    <!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style type="">
    	.nomargin {
    		margin-left: 0px;
    	}
    </style>

app/views/layouts/_footer.html.erb
<p class="nomargin">Copyright Fejiro O.</P>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Yelpdemo</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/pages/about">About</a></li>
        <li><a href="/pages/contact">Contact</a></li>
        
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Yelpdemo</title>
    <%= csrf_meta_tags %>
    <%=render 'layouts/bootstrap' %>
</head>
<body>
	<%=render 'layouts/navbar' %>
	<div class="container-fluid">
		<%= yield %>
		<%=render 'layouts/footer' %>
	</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>Welcome to Yelpdemo</h1>
<h2>This is one of the sample application for <a href="http://www.baserails.com">BaseRails</a>, a platform that teaches people to build awesome custom websites with the Ruby programming language. Sign up and start learning today!</h2>

app/views/pages/contact.html.erb
<p>Contact us at feji.cuban@gmail.com</p>

app/views/resturants/_form.html.erb
<%= form_for(resturant) do |f| %>
  <% if resturant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resturant.errors.count, "error") %> prohibited this resturant from being saved:</h2>

      <ul>
      <% resturant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :phone %>
    <%= f.text_field :phone, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :website %>
    <%= f.text_field :website, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/resturants/edit.html.erb
<h1>Editing Resturant</h1>

<%= render 'form', resturant: @resturant %>

<%= link_to 'Show', @resturant, class: "btn btn-link" %> |
<%= link_to 'Back', resturants_path, class: "btn btn-link" %>

app/views/resturants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Resturants</h1>

<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Website</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resturants.each do |resturant| %>
      <tr>
        <td><%= resturant.name %></td>
        <td><%= resturant.phone %></td>
        <td><%= resturant.website %></td>
        <td><%= link_to 'Show', resturant, class: "btn btn-link" %></td>
        <td><%= link_to 'Edit', edit_resturant_path(resturant), class: "btn btn-link" %></td>
        <td><%= link_to 'Destroy', resturant, method: :delete, data: { confirm: 'Are you sure?' },  class: "btn btn-link" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resturant', new_resturant_path,  class: "btn btn-link" %>

app/views/resturants/new.html.erb
<h1>New Resturant</h1>

<%= render 'form', resturant: @resturant %>

<%= link_to 'Back', resturants_path,  class: "btn btn-link" %>

app/views/resturants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @resturant.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @resturant.phone %>
</p>

<p>
  <strong>Website:</strong>
  <%= @resturant.website %>
</p>

<%= link_to 'Edit', edit_resturant_path(@resturant),  class: "btn btn-link" %> |
<%= link_to 'Back', resturants_path,  class: "btn btn-link" %>